//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet_Cli_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public string RgUsuario { get; set; }
        public string NomeComp { get; set; }
        public string CPF { get; set; }
        public string Telefone { get; set; }
        public string Cep { get; set; }
        public string UF { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Referencia { get; set; }
    }
}
