//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet_Cli_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public int IdPet { get; set; }
        public string NomePet { get; set; }
        public System.DateTime Nascimento { get; set; }
        public string RgUsuario { get; set; }
        public string Especie { get; set; }
        public string Raca { get; set; }
        public System.DateTime UltimaConsulta { get; set; }
        public System.DateTime ProximaConsulta { get; set; }
        public string Historico { get; set; }
        public string RgVet { get; set; }
    }
}
