//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet_Cli_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUsers
    {
        public int IdUsuario { get; set; }
        public string RgUsuario { get; set; }
        public string NomeComp { get; set; }
        public string senha { get; set; }
        public string Cargo { get; set; }
    }
}
