//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet_Cli_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veterinarios
    {
        public int IdVeterinario { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public string Telefone { get; set; }
        public string Especialidade { get; set; }
    }
}
